[package]
name = "allnodes-solana"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
allnodes-client = { workspace = true }
allnodes-service-protos = { workspace = true }
core_affinity = { workspace = true }
log = { workspace = true }
solana-entry = { workspace = true }
solana-gossip = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }

[lints]
workspace = true
